### PR TITLE
Remove configstore - fixing npm vulnerability

### PR DESCRIPTION
**Pull request by herecydev**
Resolves https://www.npmjs.com/advisories/1213 and by extension https://github.com/gatsbyjs/gatsby/issues/26128

I couldn't see any use of this package @davewasmer. Let me know if I'm incorrect.

### CODE REVIEW

**Comment by herecydev** [comment]
@davewasmer do you have any comments with this PR? It would be really good to remove the vulnerability from Gatsby (which is dependant on this change)

**Comment by hoobdeebla** [comment]
cc @zetlen

**Comment by JackHowa** [comment]
should I keep #64 open upgrading `configstore` or is removing it the priority? sorry to bother @zetlen

**Comment by herecydev** [comment]
The reason I opened this PR is because I'm pretty sure it's not used. So removing it would be preferable. If it turns out it is used then we can go with your PR.

**Comment by Js-Brecht** [comment]
I believe `configstore` was a part of the initial development effort, but its intended usage never made it to the remote
https://github.com/davewasmer/devcert/commit/967e4c165a0064ef46e7d70f064a000d41015d97

Looks like that import was stripped in January 2018:
https://github.com/davewasmer/devcert/commit/e0ad2d6f663309f339d76fa7bfaa12ccec44b09c#diff-f41e9d04a45c83f3b6f6e630f10117feL12

I can't find its implementation in `devcert-san`, either.  So according to the history, it only ever appeared as an import in `index.ts`... its intended purpose may be forever lost.  I'm all for getting rid of it.  Might as well get rid of `@types/configstore`, too.

**Comment by JackHowa** [comment]
thanks @Js-Brecht. I will close mine #64 then to reduce confusion

**Comment by zetlen** [comment]
Thanks for your patience, folks. I'm reviewing this now; I think it's likely that `configstore` is no longer used, but I'll check.

**Pull request merged**
